#!/usr/bin/perl -w

my $num = $ARGV[0];

print "$num = ";
do {
	$num2 = factor($num);
	print "$num2 x ";
	if ($num == $num2) {
		print "\n";
		exit;
	}
	$num /= $num2;
} while (1);


sub factor {
	$z = $x = shift;

	for ($y = 2; $y < ($x/$y) + 1; $y++) { return $y if $x/$y == int($x/$y); }
	return $z;
}
